### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by hezymal** [AlexanderMekumyanov/SerKnight#2]
Трудно переключаться с клавиатуры на мышку и кликать на диалоги, может ограничимся клавиатурой, или просто добавить hotkey для диалогов? 
Например:
~ "Далее" - нажать Enter
~ Если в дальнейшем появятся возможность выбора ответа, кнопки: 1, 2, 3, ...

**Comment by AlexanderMekumyanov** [comment]
Да. Ое
